### ISSUE TITLE
Trying to compile for D855

### ISSUE THREAD

**Issue by jeal0us** [XPerience-AOSP-Lollipop/Manifest#7]
Hello!
Downloaded kernel, device tree, vendor and all dependencies but I recive this error when start to compiling. 

build/core/product_config.mk:245: *** Can not locate config makefile for product "xpe_d855".  Stop.
Did not get local manifest, will create a new one
Did not get local manifest, will create a new one
Going to fetch xpe_d855 from XPerience-AOSP-Lollipop github
Checked dependency tree over : 
    NO_DEPS:		device/*/xpe_d855
build/core/product_config.mk:245: *** Can not locate config makefile for product "xpe_d855".  Stop.
build/core/product_config.mk:245: *** Can not locate config makefile for product "xpe_d855".  Stop.

** Don't have a product spec for: 'xpe_d855'
** Do you have the right repo manifest?

**Comment by Klozz** [comment]
OR Manually

$ . build/envsetup.sh
$ lunch device-userdebug
$ make bacon -j8

**Comment by jeal0us** [comment]
Hello! This is manually method. Tried manually and ./rom-build.sh with no luck

**Comment by Klozz** [comment]
Have u edited the repos to get working on xpe?

**Comment by jeal0us** [comment]
Yes, all edited and downloaded all dependecies from d885 tree and
g3-common.

Pe 17 mai 2017 06:55, "klozz (TeamMEX)" <notifications@github.com> a scris:

**Comment by Klozz** [comment]
ok then don't do lunch
only do 
. build/envsetup.sh
breakfast devicename
mka bacon -jnumberofjobssupported
or make bacon  -jnumberofjobssupported

If u have the correct xpe.mk file u can compile now =)

**Comment by traiansimedru** [comment]
Thx for your help Klozz :) And what is need to be official maintainer?

Pe 17 mai 2017 10:15, "klozz (TeamMEX)" <notifications@github.com> a scris:

**Comment by Klozz** [comment]
[quote=]Thx for your help Klozz :) And what is need to be official maintainer?

>  You agree to keep your device and do not leave it forgotten like the other "maintainers"

**Comment by jeal0us** [comment]
Yeah I know there is a lot of maintainers doing this. Can I talk with you
on Hangouts?

2017-05-23 1:03 GMT+03:00 klozz (TeamMEX) <notifications@github.com>:

**Comment by jeal0us** [comment]
Another compilation error...

make: Leaving directory `/home/slacker/WORKSPACE/XPE/kernel/lge/g3'
Building DTBs
make: Entering directory `/home/slacker/WORKSPACE/XPE/kernel/lge/g3'
make[2]: Nothing to be done for `arch/arm/boot/dtbs'.
make: Leaving directory `/home/slacker/WORKSPACE/XPE/kernel/lge/g3'
Kernel Modules not enabled
[  0% 104/20887] build
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack
FAILED:
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack
/bin/bash -c "(mkdir -p
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack.tmpjill.res
) && (unzip -qo prebuilts/sdk/20/android.jar -d
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack.tmpjill.res
) && (find
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack.tmpjill.res
-iname \"*.class\" -delete ) && (JACK_VERSION=3.36.CANDIDATE
/home/slacker/WORKSPACE/XPE/out/host/linux-x86/bin/jack
@build/core/jack-default.args --verbose error  -D
jack.import.resource.policy=keep-first -D
jack.import.type.policy=keep-first -D jack.android.min-api-level=1 --import
prebuilts/sdk/20/android.jar --import-resource
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack.tmpjill.res
--output-jack
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack
) && (rm -rf
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack.tmpjill.res
)"
Communication error with Jack server (28). Try 'jack-diagnose'
[  0% 104/20887] Building with Jack:
/home/slacker/WORKSPACE/XPE/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/with-local/classes.dex
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1
make: Leaving directory `/home/slacker/WORKSPACE/XPE'


2017-05-23 6:29 GMT+03:00 Traian Simedru <tsimedru990@gmail.com>:

**Comment by jeal0us** [comment]
Solved! Everything now work great! Thank you very much Klozz for your help!! :)
